// SPDX-License-Identifier: MIT
// Copyright (C) 2026 WireHush. All Rights Reserved.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: protocol/wirehush.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Scope int32

const (
	Scope_SCOPE_UNSPECIFIED Scope = 0
	Scope_SCOPE_PRIVATE     Scope = 1
	Scope_SCOPE_SHARED      Scope = 2
)

// Enum value maps for Scope.
var (
	Scope_name = map[int32]string{
		0: "SCOPE_UNSPECIFIED",
		1: "SCOPE_PRIVATE",
		2: "SCOPE_SHARED",
	}
	Scope_value = map[string]int32{
		"SCOPE_UNSPECIFIED": 0,
		"SCOPE_PRIVATE":     1,
		"SCOPE_SHARED":      2,
	}
)

func (x Scope) Enum() *Scope {
	p := new(Scope)
	*p = x
	return p
}

func (x Scope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Scope) Descriptor() protoreflect.EnumDescriptor {
	return file_protocol_wirehush_proto_enumTypes[0].Descriptor()
}

func (Scope) Type() protoreflect.EnumType {
	return &file_protocol_wirehush_proto_enumTypes[0]
}

func (x Scope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Scope.Descriptor instead.
func (Scope) EnumDescriptor() ([]byte, []int) {
	return file_protocol_wirehush_proto_rawDescGZIP(), []int{0}
}

type TunnelState int32

const (
	TunnelState_TUNNEL_STATE_UNKNOWN   TunnelState = 0
	TunnelState_TUNNEL_STATE_STOPPED   TunnelState = 1
	TunnelState_TUNNEL_STATE_STARTING  TunnelState = 2
	TunnelState_TUNNEL_STATE_CONNECTED TunnelState = 3
	TunnelState_TUNNEL_STATE_STOPPING  TunnelState = 4
)

// Enum value maps for TunnelState.
var (
	TunnelState_name = map[int32]string{
		0: "TUNNEL_STATE_UNKNOWN",
		1: "TUNNEL_STATE_STOPPED",
		2: "TUNNEL_STATE_STARTING",
		3: "TUNNEL_STATE_CONNECTED",
		4: "TUNNEL_STATE_STOPPING",
	}
	TunnelState_value = map[string]int32{
		"TUNNEL_STATE_UNKNOWN":   0,
		"TUNNEL_STATE_STOPPED":   1,
		"TUNNEL_STATE_STARTING":  2,
		"TUNNEL_STATE_CONNECTED": 3,
		"TUNNEL_STATE_STOPPING":  4,
	}
)

func (x TunnelState) Enum() *TunnelState {
	p := new(TunnelState)
	*p = x
	return p
}

func (x TunnelState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TunnelState) Descriptor() protoreflect.EnumDescriptor {
	return file_protocol_wirehush_proto_enumTypes[1].Descriptor()
}

func (TunnelState) Type() protoreflect.EnumType {
	return &file_protocol_wirehush_proto_enumTypes[1]
}

func (x TunnelState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TunnelState.Descriptor instead.
func (TunnelState) EnumDescriptor() ([]byte, []int) {
	return file_protocol_wirehush_proto_rawDescGZIP(), []int{1}
}

type Capability int32

const (
	Capability_CAPABILITY_UNSPECIFIED        Capability = 0
	Capability_CAPABILITY_TUNNELS            Capability = 1
	Capability_CAPABILITY_ENCRYPTED_DNS      Capability = 2
	Capability_CAPABILITY_BOOTSTRAP_SETTINGS Capability = 3
	Capability_CAPABILITY_EVENTS             Capability = 4
	Capability_CAPABILITY_EXPORT             Capability = 5
	Capability_CAPABILITY_SHARED_CREATE      Capability = 6
	Capability_CAPABILITY_SESSION_EXIT       Capability = 7
)

// Enum value maps for Capability.
var (
	Capability_name = map[int32]string{
		0: "CAPABILITY_UNSPECIFIED",
		1: "CAPABILITY_TUNNELS",
		2: "CAPABILITY_ENCRYPTED_DNS",
		3: "CAPABILITY_BOOTSTRAP_SETTINGS",
		4: "CAPABILITY_EVENTS",
		5: "CAPABILITY_EXPORT",
		6: "CAPABILITY_SHARED_CREATE",
		7: "CAPABILITY_SESSION_EXIT",
	}
	Capability_value = map[string]int32{
		"CAPABILITY_UNSPECIFIED":        0,
		"CAPABILITY_TUNNELS":            1,
		"CAPABILITY_ENCRYPTED_DNS":      2,
		"CAPABILITY_BOOTSTRAP_SETTINGS": 3,
		"CAPABILITY_EVENTS":             4,
		"CAPABILITY_EXPORT":             5,
		"CAPABILITY_SHARED_CREATE":      6,
		"CAPABILITY_SESSION_EXIT":       7,
	}
)

func (x Capability) Enum() *Capability {
	p := new(Capability)
	*p = x
	return p
}

func (x Capability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Capability) Descriptor() protoreflect.EnumDescriptor {
	return file_protocol_wirehush_proto_enumTypes[2].Descriptor()
}

func (Capability) Type() protoreflect.EnumType {
	return &file_protocol_wirehush_proto_enumTypes[2]
}

func (x Capability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Capability.Descriptor instead.
func (Capability) EnumDescriptor() ([]byte, []int) {
	return file_protocol_wirehush_proto_rawDescGZIP(), []int{2}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_protocol_wirehush_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_wirehush_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_protocol_wirehush_proto_rawDescGZIP(), []int{0}
}

type HandshakeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProtocolMajor uint32                 `protobuf:"varint,1,opt,name=protocol_major,json=protocolMajor,proto3" json:"protocol_major,omitempty"`
	ProtocolMinor uint32                 `protobuf:"varint,2,opt,name=protocol_minor,json=protocolMinor,proto3" json:"protocol_minor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_protocol_wirehush_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_wirehush_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_protocol_wirehush_proto_rawDescGZIP(), []int{1}
}

func (x *HandshakeRequest) GetProtocolMajor() uint32 {
	if x != nil {
		return x.ProtocolMajor
	}
	return 0
}

func (x *HandshakeRequest) GetProtocolMinor() uint32 {
	if x != nil {
		return x.ProtocolMinor
	}
	return 0
}

type HandshakeReply struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ProtocolMajor          uint32                 `protobuf:"varint,1,opt,name=protocol_major,json=protocolMajor,proto3" json:"protocol_major,omitempty"`
	ProtocolMinor          uint32                 `protobuf:"varint,2,opt,name=protocol_minor,json=protocolMinor,proto3" json:"protocol_minor,omitempty"`
	ProductVersion         string                 `protobuf:"bytes,3,opt,name=product_version,json=productVersion,proto3" json:"product_version,omitempty"`
	Capabilities           []Capability           `protobuf:"varint,4,rep,packed,name=capabilities,proto3,enum=wirehush.v1.Capability" json:"capabilities,omitempty"`
	InstanceId             string                 `protobuf:"bytes,5,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	MayEditShared          bool                   `protobuf:"varint,6,opt,name=may_edit_shared,json=mayEditShared,proto3" json:"may_edit_shared,omitempty"`
	MayEditMachineSettings bool                   `protobuf:"varint,7,opt,name=may_edit_machine_settings,json=mayEditMachineSettings,proto3" json:"may_edit_machine_settings,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *HandshakeReply) Reset() {
	*x = HandshakeReply{}
	mi := &file_protocol_wirehush_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeReply) ProtoMessage() {}

func (x *HandshakeReply) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_wirehush_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeReply.ProtoReflect.Descriptor instead.
func (*HandshakeReply) Descriptor() ([]byte, []int) {
	return file_protocol_wirehush_proto_rawDescGZIP(), []int{2}
}

func (x *HandshakeReply) GetProtocolMajor() uint32 {
	if x != nil {
		return x.ProtocolMajor
	}
	return 0
}

func (x *HandshakeReply) GetProtocolMinor() uint32 {
	if x != nil {
		return x.ProtocolMinor
	}
	return 0
}

func (x *HandshakeReply) GetProductVersion() string {
	if x != nil {
		return x.ProductVersion
	}
	return ""
}

func (x *HandshakeReply) GetCapabilities() []Capability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *HandshakeReply) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *HandshakeReply) GetMayEditShared() bool {
	if x != nil {
		return x.MayEditShared
	}
	return false
}

func (x *HandshakeReply) GetMayEditMachineSettings() bool {
	if x != nil {
		return x.MayEditMachineSettings
	}
	return false
}

type TunnelRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TunnelId      string                 `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	Scope         Scope                  `protobuf:"varint,2,opt,name=scope,proto3,enum=wirehush.v1.Scope" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelRef) Reset() {
	*x = TunnelRef{}
	mi := &file_protocol_wirehush_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelRef) ProtoMessage() {}

func (x *TunnelRef) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_wirehush_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelRef.ProtoReflect.Descriptor instead.
func (*TunnelRef) Descriptor() ([]byte, []int) {
	return file_protocol_wirehush_proto_rawDescGZIP(), []int{3}
}

func (x *TunnelRef) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

func (x *TunnelRef) GetScope() Scope {
	if x != nil {
		return x.Scope
	}
	return Scope_SCOPE_UNSPECIFIED
}

type TunnelSnapshot struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Tunnel              *TunnelRef             `protobuf:"bytes,1,opt,name=tunnel,proto3" json:"tunnel,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	State               TunnelState            `protobuf:"varint,3,opt,name=state,proto3,enum=wirehush.v1.TunnelState" json:"state,omitempty"`
	EncryptedDns        bool                   `protobuf:"varint,4,opt,name=encrypted_dns,json=encryptedDns,proto3" json:"encrypted_dns,omitempty"`
	RxBytes             *uint64                `protobuf:"varint,5,opt,name=rx_bytes,json=rxBytes,proto3,oneof" json:"rx_bytes,omitempty"`
	TxBytes             *uint64                `protobuf:"varint,6,opt,name=tx_bytes,json=txBytes,proto3,oneof" json:"tx_bytes,omitempty"`
	LatestHandshakeUnix *int64                 `protobuf:"varint,7,opt,name=latest_handshake_unix,json=latestHandshakeUnix,proto3,oneof" json:"latest_handshake_unix,omitempty"`
	MayEdit             bool                   `protobuf:"varint,8,opt,name=may_edit,json=mayEdit,proto3" json:"may_edit,omitempty"`
	MayExport           bool                   `protobuf:"varint,9,opt,name=may_export,json=mayExport,proto3" json:"may_export,omitempty"`
	// Status fields are absent when not established by actual runtime evidence.
	DnsReady      *bool `protobuf:"varint,10,opt,name=dns_ready,json=dnsReady,proto3,oneof" json:"dns_ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelSnapshot) Reset() {
	*x = TunnelSnapshot{}
	mi := &file_protocol_wirehush_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelSnapshot) ProtoMessage() {}

func (x *TunnelSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_wirehush_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelSnapshot.ProtoReflect.Descriptor instead.
func (*TunnelSnapshot) Descriptor() ([]byte, []int) {
	return file_protocol_wirehush_proto_rawDescGZIP(), []int{4}
}

func (x *TunnelSnapshot) GetTunnel() *TunnelRef {
	if x != nil {
		return x.Tunnel
	}
	return nil
}

func (x *TunnelSnapshot) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TunnelSnapshot) GetState() TunnelState {
	if x != nil {
		return x.State
	}
	return TunnelState_TUNNEL_STATE_UNKNOWN
}

func (x *TunnelSnapshot) GetEncryptedDns() bool {
	if x != nil {
		return x.EncryptedDns
	}
	return false
}

func (x *TunnelSnapshot) GetRxBytes() uint64 {
	if x != nil && x.RxBytes != nil {
		return *x.RxBytes
	}
	return 0
}

func (x *TunnelSnapshot) GetTxBytes() uint64 {
	if x != nil && x.TxBytes != nil {
		return *x.TxBytes
	}
	return 0
}

func (x *TunnelSnapshot) GetLatestHandshakeUnix() int64 {
	if x != nil && x.LatestHandshakeUnix != nil {
		return *x.LatestHandshakeUnix
	}
	return 0
}

func (x *TunnelSnapshot) GetMayEdit() bool {
	if x != nil {
		return x.MayEdit
	}
	return false
}

func (x *TunnelSnapshot) GetMayExport() bool {
	if x != nil {
		return x.MayExport
	}
	return false
}

func (x *TunnelSnapshot) GetDnsReady() bool {
	if x != nil && x.DnsReady != nil {
		return *x.DnsReady
	}
	return false
}

type SnapshotReply struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	InstanceId               string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Revision                 uint64                 `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	Tunnels                  []*TunnelSnapshot      `protobuf:"bytes,3,rep,name=tunnels,proto3" json:"tunnels,omitempty"`
	DeviceBusyForAnotherUser bool                   `protobuf:"varint,4,opt,name=device_busy_for_another_user,json=deviceBusyForAnotherUser,proto3" json:"device_busy_for_another_user,omitempty"`
	ManagerClosing           bool                   `protobuf:"varint,5,opt,name=manager_closing,json=managerClosing,proto3" json:"manager_closing,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *SnapshotReply) Reset() {
	*x = SnapshotReply{}
	mi := &file_protocol_wirehush_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotReply) ProtoMessage() {}

func (x *SnapshotReply) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_wirehush_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotReply.ProtoReflect.Descriptor instead.
func (*SnapshotReply) Descriptor() ([]byte, []int) {
	return file_protocol_wirehush_proto_rawDescGZIP(), []int{5}
}

func (x *SnapshotReply) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *SnapshotReply) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *SnapshotReply) GetTunnels() []*TunnelSnapshot {
	if x != nil {
		return x.Tunnels
	}
	return nil
}

func (x *SnapshotReply) GetDeviceBusyForAnotherUser() bool {
	if x != nil {
		return x.DeviceBusyForAnotherUser
	}
	return false
}

func (x *SnapshotReply) GetManagerClosing() bool {
	if x != nil {
		return x.ManagerClosing
	}
	return false
}

type ConfigurationReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ordinary WG-quick export only; no WireHush metadata is injected.
	WgQuickText   string `protobuf:"bytes,1,opt,name=wg_quick_text,json=wgQuickText,proto3" json:"wg_quick_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigurationReply) Reset() {
	*x = ConfigurationReply{}
	mi := &file_protocol_wirehush_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationReply) ProtoMessage() {}

func (x *ConfigurationReply) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_wirehush_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationReply.ProtoReflect.Descriptor instead.
func (*ConfigurationReply) Descriptor() ([]byte, []int) {
	return file_protocol_wirehush_proto_rawDescGZIP(), []int{6}
}

func (x *ConfigurationReply) GetWgQuickText() string {
	if x != nil {
		return x.WgQuickText
	}
	return ""
}

type CreateTunnelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         Scope                  `protobuf:"varint,1,opt,name=scope,proto3,enum=wirehush.v1.Scope" json:"scope,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	WgQuickText   string                 `protobuf:"bytes,3,opt,name=wg_quick_text,json=wgQuickText,proto3" json:"wg_quick_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTunnelRequest) Reset() {
	*x = CreateTunnelRequest{}
	mi := &file_protocol_wirehush_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTunnelRequest) ProtoMessage() {}

func (x *CreateTunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_wirehush_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTunnelRequest.ProtoReflect.Descriptor instead.
func (*CreateTunnelRequest) Descriptor() ([]byte, []int) {
	return file_protocol_wirehush_proto_rawDescGZIP(), []int{7}
}

func (x *CreateTunnelRequest) GetScope() Scope {
	if x != nil {
		return x.Scope
	}
	return Scope_SCOPE_UNSPECIFIED
}

func (x *CreateTunnelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTunnelRequest) GetWgQuickText() string {
	if x != nil {
		return x.WgQuickText
	}
	return ""
}

type UpdateTunnelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tunnel        *TunnelRef             `protobuf:"bytes,1,opt,name=tunnel,proto3" json:"tunnel,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	WgQuickText   string                 `protobuf:"bytes,3,opt,name=wg_quick_text,json=wgQuickText,proto3" json:"wg_quick_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTunnelRequest) Reset() {
	*x = UpdateTunnelRequest{}
	mi := &file_protocol_wirehush_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTunnelRequest) ProtoMessage() {}

func (x *UpdateTunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_wirehush_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTunnelRequest.ProtoReflect.Descriptor instead.
func (*UpdateTunnelRequest) Descriptor() ([]byte, []int) {
	return file_protocol_wirehush_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateTunnelRequest) GetTunnel() *TunnelRef {
	if x != nil {
		return x.Tunnel
	}
	return nil
}

func (x *UpdateTunnelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTunnelRequest) GetWgQuickText() string {
	if x != nil {
		return x.WgQuickText
	}
	return ""
}

type BootstrapResolver struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Custom        bool                   `protobuf:"varint,3,opt,name=custom,proto3" json:"custom,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootstrapResolver) Reset() {
	*x = BootstrapResolver{}
	mi := &file_protocol_wirehush_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapResolver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapResolver) ProtoMessage() {}

func (x *BootstrapResolver) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_wirehush_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapResolver.ProtoReflect.Descriptor instead.
func (*BootstrapResolver) Descriptor() ([]byte, []int) {
	return file_protocol_wirehush_proto_rawDescGZIP(), []int{9}
}

func (x *BootstrapResolver) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *BootstrapResolver) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *BootstrapResolver) GetCustom() bool {
	if x != nil {
		return x.Custom
	}
	return false
}

type BootstrapSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resolvers     []*BootstrapResolver   `protobuf:"bytes,1,rep,name=resolvers,proto3" json:"resolvers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootstrapSettings) Reset() {
	*x = BootstrapSettings{}
	mi := &file_protocol_wirehush_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapSettings) ProtoMessage() {}

func (x *BootstrapSettings) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_wirehush_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapSettings.ProtoReflect.Descriptor instead.
func (*BootstrapSettings) Descriptor() ([]byte, []int) {
	return file_protocol_wirehush_proto_rawDescGZIP(), []int{10}
}

func (x *BootstrapSettings) GetResolvers() []*BootstrapResolver {
	if x != nil {
		return x.Resolvers
	}
	return nil
}

type ExitReply struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CleanupComplete bool                   `protobuf:"varint,1,opt,name=cleanup_complete,json=cleanupComplete,proto3" json:"cleanup_complete,omitempty"`
	ManagerStopping bool                   `protobuf:"varint,2,opt,name=manager_stopping,json=managerStopping,proto3" json:"manager_stopping,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExitReply) Reset() {
	*x = ExitReply{}
	mi := &file_protocol_wirehush_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExitReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitReply) ProtoMessage() {}

func (x *ExitReply) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_wirehush_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitReply.ProtoReflect.Descriptor instead.
func (*ExitReply) Descriptor() ([]byte, []int) {
	return file_protocol_wirehush_proto_rawDescGZIP(), []int{11}
}

func (x *ExitReply) GetCleanupComplete() bool {
	if x != nil {
		return x.CleanupComplete
	}
	return false
}

func (x *ExitReply) GetManagerStopping() bool {
	if x != nil {
		return x.ManagerStopping
	}
	return false
}

var File_protocol_wirehush_proto protoreflect.FileDescriptor

const file_protocol_wirehush_proto_rawDesc = "" +
	"\n" +
	"\x17protocol/wirehush.proto\x12\vwirehush.v1\"\a\n" +
	"\x05Empty\"`\n" +
	"\x10HandshakeRequest\x12%\n" +
	"\x0eprotocol_major\x18\x01 \x01(\rR\rprotocolMajor\x12%\n" +
	"\x0eprotocol_minor\x18\x02 \x01(\rR\rprotocolMinor\"\xc8\x02\n" +
	"\x0eHandshakeReply\x12%\n" +
	"\x0eprotocol_major\x18\x01 \x01(\rR\rprotocolMajor\x12%\n" +
	"\x0eprotocol_minor\x18\x02 \x01(\rR\rprotocolMinor\x12'\n" +
	"\x0fproduct_version\x18\x03 \x01(\tR\x0eproductVersion\x12;\n" +
	"\fcapabilities\x18\x04 \x03(\x0e2\x17.wirehush.v1.CapabilityR\fcapabilities\x12\x1f\n" +
	"\vinstance_id\x18\x05 \x01(\tR\n" +
	"instanceId\x12&\n" +
	"\x0fmay_edit_shared\x18\x06 \x01(\bR\rmayEditShared\x129\n" +
	"\x19may_edit_machine_settings\x18\a \x01(\bR\x16mayEditMachineSettings\"R\n" +
	"\tTunnelRef\x12\x1b\n" +
	"\ttunnel_id\x18\x01 \x01(\tR\btunnelId\x12(\n" +
	"\x05scope\x18\x02 \x01(\x0e2\x12.wirehush.v1.ScopeR\x05scope\"\xc0\x03\n" +
	"\x0eTunnelSnapshot\x12.\n" +
	"\x06tunnel\x18\x01 \x01(\v2\x16.wirehush.v1.TunnelRefR\x06tunnel\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12.\n" +
	"\x05state\x18\x03 \x01(\x0e2\x18.wirehush.v1.TunnelStateR\x05state\x12#\n" +
	"\rencrypted_dns\x18\x04 \x01(\bR\fencryptedDns\x12\x1e\n" +
	"\brx_bytes\x18\x05 \x01(\x04H\x00R\arxBytes\x88\x01\x01\x12\x1e\n" +
	"\btx_bytes\x18\x06 \x01(\x04H\x01R\atxBytes\x88\x01\x01\x127\n" +
	"\x15latest_handshake_unix\x18\a \x01(\x03H\x02R\x13latestHandshakeUnix\x88\x01\x01\x12\x19\n" +
	"\bmay_edit\x18\b \x01(\bR\amayEdit\x12\x1d\n" +
	"\n" +
	"may_export\x18\t \x01(\bR\tmayExport\x12 \n" +
	"\tdns_ready\x18\n" +
	" \x01(\bH\x03R\bdnsReady\x88\x01\x01B\v\n" +
	"\t_rx_bytesB\v\n" +
	"\t_tx_bytesB\x18\n" +
	"\x16_latest_handshake_unixB\f\n" +
	"\n" +
	"_dns_ready\"\xec\x01\n" +
	"\rSnapshotReply\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x04R\brevision\x125\n" +
	"\atunnels\x18\x03 \x03(\v2\x1b.wirehush.v1.TunnelSnapshotR\atunnels\x12>\n" +
	"\x1cdevice_busy_for_another_user\x18\x04 \x01(\bR\x18deviceBusyForAnotherUser\x12'\n" +
	"\x0fmanager_closing\x18\x05 \x01(\bR\x0emanagerClosing\"8\n" +
	"\x12ConfigurationReply\x12\"\n" +
	"\rwg_quick_text\x18\x01 \x01(\tR\vwgQuickText\"w\n" +
	"\x13CreateTunnelRequest\x12(\n" +
	"\x05scope\x18\x01 \x01(\x0e2\x12.wirehush.v1.ScopeR\x05scope\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\"\n" +
	"\rwg_quick_text\x18\x03 \x01(\tR\vwgQuickText\"}\n" +
	"\x13UpdateTunnelRequest\x12.\n" +
	"\x06tunnel\x18\x01 \x01(\v2\x16.wirehush.v1.TunnelRefR\x06tunnel\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\"\n" +
	"\rwg_quick_text\x18\x03 \x01(\tR\vwgQuickText\"_\n" +
	"\x11BootstrapResolver\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\x12\x16\n" +
	"\x06custom\x18\x03 \x01(\bR\x06custom\"Q\n" +
	"\x11BootstrapSettings\x12<\n" +
	"\tresolvers\x18\x01 \x03(\v2\x1e.wirehush.v1.BootstrapResolverR\tresolvers\"a\n" +
	"\tExitReply\x12)\n" +
	"\x10cleanup_complete\x18\x01 \x01(\bR\x0fcleanupComplete\x12)\n" +
	"\x10manager_stopping\x18\x02 \x01(\bR\x0fmanagerStopping*C\n" +
	"\x05Scope\x12\x15\n" +
	"\x11SCOPE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSCOPE_PRIVATE\x10\x01\x12\x10\n" +
	"\fSCOPE_SHARED\x10\x02*\x93\x01\n" +
	"\vTunnelState\x12\x18\n" +
	"\x14TUNNEL_STATE_UNKNOWN\x10\x00\x12\x18\n" +
	"\x14TUNNEL_STATE_STOPPED\x10\x01\x12\x19\n" +
	"\x15TUNNEL_STATE_STARTING\x10\x02\x12\x1a\n" +
	"\x16TUNNEL_STATE_CONNECTED\x10\x03\x12\x19\n" +
	"\x15TUNNEL_STATE_STOPPING\x10\x04*\xea\x01\n" +
	"\n" +
	"Capability\x12\x1a\n" +
	"\x16CAPABILITY_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12CAPABILITY_TUNNELS\x10\x01\x12\x1c\n" +
	"\x18CAPABILITY_ENCRYPTED_DNS\x10\x02\x12!\n" +
	"\x1dCAPABILITY_BOOTSTRAP_SETTINGS\x10\x03\x12\x15\n" +
	"\x11CAPABILITY_EVENTS\x10\x04\x12\x15\n" +
	"\x11CAPABILITY_EXPORT\x10\x05\x12\x1c\n" +
	"\x18CAPABILITY_SHARED_CREATE\x10\x06\x12\x1b\n" +
	"\x17CAPABILITY_SESSION_EXIT\x10\a2\xa6\x06\n" +
	"\aManager\x12G\n" +
	"\tHandshake\x12\x1d.wirehush.v1.HandshakeRequest\x1a\x1b.wirehush.v1.HandshakeReply\x12:\n" +
	"\bSnapshot\x12\x12.wirehush.v1.Empty\x1a\x1a.wirehush.v1.SnapshotReply\x12L\n" +
	"\x11ReadConfiguration\x12\x16.wirehush.v1.TunnelRef\x1a\x1f.wirehush.v1.ConfigurationReply\x12M\n" +
	"\fCreateTunnel\x12 .wirehush.v1.CreateTunnelRequest\x1a\x1b.wirehush.v1.TunnelSnapshot\x12D\n" +
	"\fUpdateTunnel\x12 .wirehush.v1.UpdateTunnelRequest\x1a\x12.wirehush.v1.Empty\x12:\n" +
	"\fDeleteTunnel\x12\x16.wirehush.v1.TunnelRef\x1a\x12.wirehush.v1.Empty\x129\n" +
	"\vStartTunnel\x12\x16.wirehush.v1.TunnelRef\x1a\x12.wirehush.v1.Empty\x128\n" +
	"\n" +
	"StopTunnel\x12\x16.wirehush.v1.TunnelRef\x1a\x12.wirehush.v1.Empty\x12C\n" +
	"\rReadBootstrap\x12\x12.wirehush.v1.Empty\x1a\x1e.wirehush.v1.BootstrapSettings\x12C\n" +
	"\rSaveBootstrap\x12\x1e.wirehush.v1.BootstrapSettings\x1a\x12.wirehush.v1.Empty\x12=\n" +
	"\tSubscribe\x12\x12.wirehush.v1.Empty\x1a\x1a.wirehush.v1.SnapshotReply0\x01\x129\n" +
	"\vExitSession\x12\x12.wirehush.v1.Empty\x1a\x16.wirehush.v1.ExitReplyBJZ4golang.zx2c4.com/wireguard/windows/protocol;protocol\xaa\x02\x11WireHush.Protocolb\x06proto3"

var (
	file_protocol_wirehush_proto_rawDescOnce sync.Once
	file_protocol_wirehush_proto_rawDescData []byte
)

func file_protocol_wirehush_proto_rawDescGZIP() []byte {
	file_protocol_wirehush_proto_rawDescOnce.Do(func() {
		file_protocol_wirehush_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_wirehush_proto_rawDesc), len(file_protocol_wirehush_proto_rawDesc)))
	})
	return file_protocol_wirehush_proto_rawDescData
}

var file_protocol_wirehush_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_protocol_wirehush_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_protocol_wirehush_proto_goTypes = []any{
	(Scope)(0),                  // 0: wirehush.v1.Scope
	(TunnelState)(0),            // 1: wirehush.v1.TunnelState
	(Capability)(0),             // 2: wirehush.v1.Capability
	(*Empty)(nil),               // 3: wirehush.v1.Empty
	(*HandshakeRequest)(nil),    // 4: wirehush.v1.HandshakeRequest
	(*HandshakeReply)(nil),      // 5: wirehush.v1.HandshakeReply
	(*TunnelRef)(nil),           // 6: wirehush.v1.TunnelRef
	(*TunnelSnapshot)(nil),      // 7: wirehush.v1.TunnelSnapshot
	(*SnapshotReply)(nil),       // 8: wirehush.v1.SnapshotReply
	(*ConfigurationReply)(nil),  // 9: wirehush.v1.ConfigurationReply
	(*CreateTunnelRequest)(nil), // 10: wirehush.v1.CreateTunnelRequest
	(*UpdateTunnelRequest)(nil), // 11: wirehush.v1.UpdateTunnelRequest
	(*BootstrapResolver)(nil),   // 12: wirehush.v1.BootstrapResolver
	(*BootstrapSettings)(nil),   // 13: wirehush.v1.BootstrapSettings
	(*ExitReply)(nil),           // 14: wirehush.v1.ExitReply
}
var file_protocol_wirehush_proto_depIdxs = []int32{
	2,  // 0: wirehush.v1.HandshakeReply.capabilities:type_name -> wirehush.v1.Capability
	0,  // 1: wirehush.v1.TunnelRef.scope:type_name -> wirehush.v1.Scope
	6,  // 2: wirehush.v1.TunnelSnapshot.tunnel:type_name -> wirehush.v1.TunnelRef
	1,  // 3: wirehush.v1.TunnelSnapshot.state:type_name -> wirehush.v1.TunnelState
	7,  // 4: wirehush.v1.SnapshotReply.tunnels:type_name -> wirehush.v1.TunnelSnapshot
	0,  // 5: wirehush.v1.CreateTunnelRequest.scope:type_name -> wirehush.v1.Scope
	6,  // 6: wirehush.v1.UpdateTunnelRequest.tunnel:type_name -> wirehush.v1.TunnelRef
	12, // 7: wirehush.v1.BootstrapSettings.resolvers:type_name -> wirehush.v1.BootstrapResolver
	4,  // 8: wirehush.v1.Manager.Handshake:input_type -> wirehush.v1.HandshakeRequest
	3,  // 9: wirehush.v1.Manager.Snapshot:input_type -> wirehush.v1.Empty
	6,  // 10: wirehush.v1.Manager.ReadConfiguration:input_type -> wirehush.v1.TunnelRef
	10, // 11: wirehush.v1.Manager.CreateTunnel:input_type -> wirehush.v1.CreateTunnelRequest
	11, // 12: wirehush.v1.Manager.UpdateTunnel:input_type -> wirehush.v1.UpdateTunnelRequest
	6,  // 13: wirehush.v1.Manager.DeleteTunnel:input_type -> wirehush.v1.TunnelRef
	6,  // 14: wirehush.v1.Manager.StartTunnel:input_type -> wirehush.v1.TunnelRef
	6,  // 15: wirehush.v1.Manager.StopTunnel:input_type -> wirehush.v1.TunnelRef
	3,  // 16: wirehush.v1.Manager.ReadBootstrap:input_type -> wirehush.v1.Empty
	13, // 17: wirehush.v1.Manager.SaveBootstrap:input_type -> wirehush.v1.BootstrapSettings
	3,  // 18: wirehush.v1.Manager.Subscribe:input_type -> wirehush.v1.Empty
	3,  // 19: wirehush.v1.Manager.ExitSession:input_type -> wirehush.v1.Empty
	5,  // 20: wirehush.v1.Manager.Handshake:output_type -> wirehush.v1.HandshakeReply
	8,  // 21: wirehush.v1.Manager.Snapshot:output_type -> wirehush.v1.SnapshotReply
	9,  // 22: wirehush.v1.Manager.ReadConfiguration:output_type -> wirehush.v1.ConfigurationReply
	7,  // 23: wirehush.v1.Manager.CreateTunnel:output_type -> wirehush.v1.TunnelSnapshot
	3,  // 24: wirehush.v1.Manager.UpdateTunnel:output_type -> wirehush.v1.Empty
	3,  // 25: wirehush.v1.Manager.DeleteTunnel:output_type -> wirehush.v1.Empty
	3,  // 26: wirehush.v1.Manager.StartTunnel:output_type -> wirehush.v1.Empty
	3,  // 27: wirehush.v1.Manager.StopTunnel:output_type -> wirehush.v1.Empty
	13, // 28: wirehush.v1.Manager.ReadBootstrap:output_type -> wirehush.v1.BootstrapSettings
	3,  // 29: wirehush.v1.Manager.SaveBootstrap:output_type -> wirehush.v1.Empty
	8,  // 30: wirehush.v1.Manager.Subscribe:output_type -> wirehush.v1.SnapshotReply
	14, // 31: wirehush.v1.Manager.ExitSession:output_type -> wirehush.v1.ExitReply
	20, // [20:32] is the sub-list for method output_type
	8,  // [8:20] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_protocol_wirehush_proto_init() }
func file_protocol_wirehush_proto_init() {
	if File_protocol_wirehush_proto != nil {
		return
	}
	file_protocol_wirehush_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_wirehush_proto_rawDesc), len(file_protocol_wirehush_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protocol_wirehush_proto_goTypes,
		DependencyIndexes: file_protocol_wirehush_proto_depIdxs,
		EnumInfos:         file_protocol_wirehush_proto_enumTypes,
		MessageInfos:      file_protocol_wirehush_proto_msgTypes,
	}.Build()
	File_protocol_wirehush_proto = out.File
	file_protocol_wirehush_proto_goTypes = nil
	file_protocol_wirehush_proto_depIdxs = nil
}
