// SPDX-License-Identifier: MIT
// Copyright (C) 2026 WireHush. All Rights Reserved.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.2
// source: protocol/wirehush.proto

package protocol

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Manager_Handshake_FullMethodName         = "/wirehush.v1.Manager/Handshake"
	Manager_Snapshot_FullMethodName          = "/wirehush.v1.Manager/Snapshot"
	Manager_ReadConfiguration_FullMethodName = "/wirehush.v1.Manager/ReadConfiguration"
	Manager_CreateTunnel_FullMethodName      = "/wirehush.v1.Manager/CreateTunnel"
	Manager_UpdateTunnel_FullMethodName      = "/wirehush.v1.Manager/UpdateTunnel"
	Manager_DeleteTunnel_FullMethodName      = "/wirehush.v1.Manager/DeleteTunnel"
	Manager_StartTunnel_FullMethodName       = "/wirehush.v1.Manager/StartTunnel"
	Manager_StopTunnel_FullMethodName        = "/wirehush.v1.Manager/StopTunnel"
	Manager_ReadBootstrap_FullMethodName     = "/wirehush.v1.Manager/ReadBootstrap"
	Manager_SaveBootstrap_FullMethodName     = "/wirehush.v1.Manager/SaveBootstrap"
	Manager_Subscribe_FullMethodName         = "/wirehush.v1.Manager/Subscribe"
	Manager_ExitSession_FullMethodName       = "/wirehush.v1.Manager/ExitSession"
)

// ManagerClient is the client API for Manager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Windows pipe authentication supplies caller identity; no request carries SID,
// session, authorization claims, a storage path, or a caller-selected new ID.
type ManagerClient interface {
	Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeReply, error)
	Snapshot(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SnapshotReply, error)
	ReadConfiguration(ctx context.Context, in *TunnelRef, opts ...grpc.CallOption) (*ConfigurationReply, error)
	CreateTunnel(ctx context.Context, in *CreateTunnelRequest, opts ...grpc.CallOption) (*TunnelSnapshot, error)
	UpdateTunnel(ctx context.Context, in *UpdateTunnelRequest, opts ...grpc.CallOption) (*Empty, error)
	DeleteTunnel(ctx context.Context, in *TunnelRef, opts ...grpc.CallOption) (*Empty, error)
	StartTunnel(ctx context.Context, in *TunnelRef, opts ...grpc.CallOption) (*Empty, error)
	StopTunnel(ctx context.Context, in *TunnelRef, opts ...grpc.CallOption) (*Empty, error)
	ReadBootstrap(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BootstrapSettings, error)
	SaveBootstrap(ctx context.Context, in *BootstrapSettings, opts ...grpc.CallOption) (*Empty, error)
	Subscribe(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SnapshotReply], error)
	// Stops only this caller's authorized active tunnel when safe; other sessions
	// and other-user tunnels prevent whole-manager shutdown, never authorize it.
	ExitSession(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ExitReply, error)
}

type managerClient struct {
	cc grpc.ClientConnInterface
}

func NewManagerClient(cc grpc.ClientConnInterface) ManagerClient {
	return &managerClient{cc}
}

func (c *managerClient) Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandshakeReply)
	err := c.cc.Invoke(ctx, Manager_Handshake_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) Snapshot(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SnapshotReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnapshotReply)
	err := c.cc.Invoke(ctx, Manager_Snapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) ReadConfiguration(ctx context.Context, in *TunnelRef, opts ...grpc.CallOption) (*ConfigurationReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigurationReply)
	err := c.cc.Invoke(ctx, Manager_ReadConfiguration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) CreateTunnel(ctx context.Context, in *CreateTunnelRequest, opts ...grpc.CallOption) (*TunnelSnapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TunnelSnapshot)
	err := c.cc.Invoke(ctx, Manager_CreateTunnel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) UpdateTunnel(ctx context.Context, in *UpdateTunnelRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Manager_UpdateTunnel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) DeleteTunnel(ctx context.Context, in *TunnelRef, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Manager_DeleteTunnel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) StartTunnel(ctx context.Context, in *TunnelRef, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Manager_StartTunnel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) StopTunnel(ctx context.Context, in *TunnelRef, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Manager_StopTunnel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) ReadBootstrap(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BootstrapSettings, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BootstrapSettings)
	err := c.cc.Invoke(ctx, Manager_ReadBootstrap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) SaveBootstrap(ctx context.Context, in *BootstrapSettings, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Manager_SaveBootstrap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) Subscribe(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SnapshotReply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Manager_ServiceDesc.Streams[0], Manager_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, SnapshotReply]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Manager_SubscribeClient = grpc.ServerStreamingClient[SnapshotReply]

func (c *managerClient) ExitSession(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ExitReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExitReply)
	err := c.cc.Invoke(ctx, Manager_ExitSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ManagerServer is the server API for Manager service.
// All implementations must embed UnimplementedManagerServer
// for forward compatibility.
//
// Windows pipe authentication supplies caller identity; no request carries SID,
// session, authorization claims, a storage path, or a caller-selected new ID.
type ManagerServer interface {
	Handshake(context.Context, *HandshakeRequest) (*HandshakeReply, error)
	Snapshot(context.Context, *Empty) (*SnapshotReply, error)
	ReadConfiguration(context.Context, *TunnelRef) (*ConfigurationReply, error)
	CreateTunnel(context.Context, *CreateTunnelRequest) (*TunnelSnapshot, error)
	UpdateTunnel(context.Context, *UpdateTunnelRequest) (*Empty, error)
	DeleteTunnel(context.Context, *TunnelRef) (*Empty, error)
	StartTunnel(context.Context, *TunnelRef) (*Empty, error)
	StopTunnel(context.Context, *TunnelRef) (*Empty, error)
	ReadBootstrap(context.Context, *Empty) (*BootstrapSettings, error)
	SaveBootstrap(context.Context, *BootstrapSettings) (*Empty, error)
	Subscribe(*Empty, grpc.ServerStreamingServer[SnapshotReply]) error
	// Stops only this caller's authorized active tunnel when safe; other sessions
	// and other-user tunnels prevent whole-manager shutdown, never authorize it.
	ExitSession(context.Context, *Empty) (*ExitReply, error)
	mustEmbedUnimplementedManagerServer()
}

// UnimplementedManagerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedManagerServer struct{}

func (UnimplementedManagerServer) Handshake(context.Context, *HandshakeRequest) (*HandshakeReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Handshake not implemented")
}
func (UnimplementedManagerServer) Snapshot(context.Context, *Empty) (*SnapshotReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Snapshot not implemented")
}
func (UnimplementedManagerServer) ReadConfiguration(context.Context, *TunnelRef) (*ConfigurationReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadConfiguration not implemented")
}
func (UnimplementedManagerServer) CreateTunnel(context.Context, *CreateTunnelRequest) (*TunnelSnapshot, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTunnel not implemented")
}
func (UnimplementedManagerServer) UpdateTunnel(context.Context, *UpdateTunnelRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTunnel not implemented")
}
func (UnimplementedManagerServer) DeleteTunnel(context.Context, *TunnelRef) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTunnel not implemented")
}
func (UnimplementedManagerServer) StartTunnel(context.Context, *TunnelRef) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method StartTunnel not implemented")
}
func (UnimplementedManagerServer) StopTunnel(context.Context, *TunnelRef) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method StopTunnel not implemented")
}
func (UnimplementedManagerServer) ReadBootstrap(context.Context, *Empty) (*BootstrapSettings, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadBootstrap not implemented")
}
func (UnimplementedManagerServer) SaveBootstrap(context.Context, *BootstrapSettings) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveBootstrap not implemented")
}
func (UnimplementedManagerServer) Subscribe(*Empty, grpc.ServerStreamingServer[SnapshotReply]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedManagerServer) ExitSession(context.Context, *Empty) (*ExitReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ExitSession not implemented")
}
func (UnimplementedManagerServer) mustEmbedUnimplementedManagerServer() {}
func (UnimplementedManagerServer) testEmbeddedByValue()                 {}

// UnsafeManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ManagerServer will
// result in compilation errors.
type UnsafeManagerServer interface {
	mustEmbedUnimplementedManagerServer()
}

func RegisterManagerServer(s grpc.ServiceRegistrar, srv ManagerServer) {
	// If the following call panics, it indicates UnimplementedManagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Manager_ServiceDesc, srv)
}

func _Manager_Handshake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandshakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).Handshake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Manager_Handshake_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).Handshake(ctx, req.(*HandshakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_Snapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).Snapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Manager_Snapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).Snapshot(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_ReadConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TunnelRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).ReadConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Manager_ReadConfiguration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).ReadConfiguration(ctx, req.(*TunnelRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_CreateTunnel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTunnelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).CreateTunnel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Manager_CreateTunnel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).CreateTunnel(ctx, req.(*CreateTunnelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_UpdateTunnel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTunnelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).UpdateTunnel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Manager_UpdateTunnel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).UpdateTunnel(ctx, req.(*UpdateTunnelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_DeleteTunnel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TunnelRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).DeleteTunnel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Manager_DeleteTunnel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).DeleteTunnel(ctx, req.(*TunnelRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_StartTunnel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TunnelRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).StartTunnel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Manager_StartTunnel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).StartTunnel(ctx, req.(*TunnelRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_StopTunnel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TunnelRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).StopTunnel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Manager_StopTunnel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).StopTunnel(ctx, req.(*TunnelRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_ReadBootstrap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).ReadBootstrap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Manager_ReadBootstrap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).ReadBootstrap(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_SaveBootstrap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BootstrapSettings)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).SaveBootstrap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Manager_SaveBootstrap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).SaveBootstrap(ctx, req.(*BootstrapSettings))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ManagerServer).Subscribe(m, &grpc.GenericServerStream[Empty, SnapshotReply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Manager_SubscribeServer = grpc.ServerStreamingServer[SnapshotReply]

func _Manager_ExitSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).ExitSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Manager_ExitSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).ExitSession(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Manager_ServiceDesc is the grpc.ServiceDesc for Manager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Manager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wirehush.v1.Manager",
	HandlerType: (*ManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Handshake",
			Handler:    _Manager_Handshake_Handler,
		},
		{
			MethodName: "Snapshot",
			Handler:    _Manager_Snapshot_Handler,
		},
		{
			MethodName: "ReadConfiguration",
			Handler:    _Manager_ReadConfiguration_Handler,
		},
		{
			MethodName: "CreateTunnel",
			Handler:    _Manager_CreateTunnel_Handler,
		},
		{
			MethodName: "UpdateTunnel",
			Handler:    _Manager_UpdateTunnel_Handler,
		},
		{
			MethodName: "DeleteTunnel",
			Handler:    _Manager_DeleteTunnel_Handler,
		},
		{
			MethodName: "StartTunnel",
			Handler:    _Manager_StartTunnel_Handler,
		},
		{
			MethodName: "StopTunnel",
			Handler:    _Manager_StopTunnel_Handler,
		},
		{
			MethodName: "ReadBootstrap",
			Handler:    _Manager_ReadBootstrap_Handler,
		},
		{
			MethodName: "SaveBootstrap",
			Handler:    _Manager_SaveBootstrap_Handler,
		},
		{
			MethodName: "ExitSession",
			Handler:    _Manager_ExitSession_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _Manager_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protocol/wirehush.proto",
}
