// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: protocol/wirehush.proto
// </auto-generated>
// Original file comments:
// SPDX-License-Identifier: MIT
// Copyright (C) 2026 WireHush. All Rights Reserved.
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace WireHush.Protocol {
  /// <summary>
  /// Windows pipe authentication supplies caller identity; no request carries SID,
  /// session, authorization claims, a storage path, or a caller-selected new ID.
  /// </summary>
  public static partial class Manager
  {
    static readonly string __ServiceName = "wirehush.v1.Manager";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::WireHush.Protocol.HandshakeRequest> __Marshaller_wirehush_v1_HandshakeRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::WireHush.Protocol.HandshakeRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::WireHush.Protocol.HandshakeReply> __Marshaller_wirehush_v1_HandshakeReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::WireHush.Protocol.HandshakeReply.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::WireHush.Protocol.Empty> __Marshaller_wirehush_v1_Empty = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::WireHush.Protocol.Empty.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::WireHush.Protocol.SnapshotReply> __Marshaller_wirehush_v1_SnapshotReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::WireHush.Protocol.SnapshotReply.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::WireHush.Protocol.TunnelRef> __Marshaller_wirehush_v1_TunnelRef = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::WireHush.Protocol.TunnelRef.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::WireHush.Protocol.ConfigurationReply> __Marshaller_wirehush_v1_ConfigurationReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::WireHush.Protocol.ConfigurationReply.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::WireHush.Protocol.CreateTunnelRequest> __Marshaller_wirehush_v1_CreateTunnelRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::WireHush.Protocol.CreateTunnelRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::WireHush.Protocol.TunnelSnapshot> __Marshaller_wirehush_v1_TunnelSnapshot = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::WireHush.Protocol.TunnelSnapshot.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::WireHush.Protocol.UpdateTunnelRequest> __Marshaller_wirehush_v1_UpdateTunnelRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::WireHush.Protocol.UpdateTunnelRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::WireHush.Protocol.BootstrapSettings> __Marshaller_wirehush_v1_BootstrapSettings = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::WireHush.Protocol.BootstrapSettings.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::WireHush.Protocol.ExitReply> __Marshaller_wirehush_v1_ExitReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::WireHush.Protocol.ExitReply.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::WireHush.Protocol.HandshakeRequest, global::WireHush.Protocol.HandshakeReply> __Method_Handshake = new grpc::Method<global::WireHush.Protocol.HandshakeRequest, global::WireHush.Protocol.HandshakeReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Handshake",
        __Marshaller_wirehush_v1_HandshakeRequest,
        __Marshaller_wirehush_v1_HandshakeReply);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::WireHush.Protocol.Empty, global::WireHush.Protocol.SnapshotReply> __Method_Snapshot = new grpc::Method<global::WireHush.Protocol.Empty, global::WireHush.Protocol.SnapshotReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Snapshot",
        __Marshaller_wirehush_v1_Empty,
        __Marshaller_wirehush_v1_SnapshotReply);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::WireHush.Protocol.TunnelRef, global::WireHush.Protocol.ConfigurationReply> __Method_ReadConfiguration = new grpc::Method<global::WireHush.Protocol.TunnelRef, global::WireHush.Protocol.ConfigurationReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ReadConfiguration",
        __Marshaller_wirehush_v1_TunnelRef,
        __Marshaller_wirehush_v1_ConfigurationReply);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::WireHush.Protocol.CreateTunnelRequest, global::WireHush.Protocol.TunnelSnapshot> __Method_CreateTunnel = new grpc::Method<global::WireHush.Protocol.CreateTunnelRequest, global::WireHush.Protocol.TunnelSnapshot>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateTunnel",
        __Marshaller_wirehush_v1_CreateTunnelRequest,
        __Marshaller_wirehush_v1_TunnelSnapshot);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::WireHush.Protocol.UpdateTunnelRequest, global::WireHush.Protocol.Empty> __Method_UpdateTunnel = new grpc::Method<global::WireHush.Protocol.UpdateTunnelRequest, global::WireHush.Protocol.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UpdateTunnel",
        __Marshaller_wirehush_v1_UpdateTunnelRequest,
        __Marshaller_wirehush_v1_Empty);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::WireHush.Protocol.TunnelRef, global::WireHush.Protocol.Empty> __Method_DeleteTunnel = new grpc::Method<global::WireHush.Protocol.TunnelRef, global::WireHush.Protocol.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteTunnel",
        __Marshaller_wirehush_v1_TunnelRef,
        __Marshaller_wirehush_v1_Empty);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::WireHush.Protocol.TunnelRef, global::WireHush.Protocol.Empty> __Method_StartTunnel = new grpc::Method<global::WireHush.Protocol.TunnelRef, global::WireHush.Protocol.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "StartTunnel",
        __Marshaller_wirehush_v1_TunnelRef,
        __Marshaller_wirehush_v1_Empty);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::WireHush.Protocol.TunnelRef, global::WireHush.Protocol.Empty> __Method_StopTunnel = new grpc::Method<global::WireHush.Protocol.TunnelRef, global::WireHush.Protocol.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "StopTunnel",
        __Marshaller_wirehush_v1_TunnelRef,
        __Marshaller_wirehush_v1_Empty);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::WireHush.Protocol.Empty, global::WireHush.Protocol.BootstrapSettings> __Method_ReadBootstrap = new grpc::Method<global::WireHush.Protocol.Empty, global::WireHush.Protocol.BootstrapSettings>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ReadBootstrap",
        __Marshaller_wirehush_v1_Empty,
        __Marshaller_wirehush_v1_BootstrapSettings);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::WireHush.Protocol.BootstrapSettings, global::WireHush.Protocol.Empty> __Method_SaveBootstrap = new grpc::Method<global::WireHush.Protocol.BootstrapSettings, global::WireHush.Protocol.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SaveBootstrap",
        __Marshaller_wirehush_v1_BootstrapSettings,
        __Marshaller_wirehush_v1_Empty);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::WireHush.Protocol.Empty, global::WireHush.Protocol.SnapshotReply> __Method_Subscribe = new grpc::Method<global::WireHush.Protocol.Empty, global::WireHush.Protocol.SnapshotReply>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "Subscribe",
        __Marshaller_wirehush_v1_Empty,
        __Marshaller_wirehush_v1_SnapshotReply);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::WireHush.Protocol.Empty, global::WireHush.Protocol.ExitReply> __Method_ExitSession = new grpc::Method<global::WireHush.Protocol.Empty, global::WireHush.Protocol.ExitReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ExitSession",
        __Marshaller_wirehush_v1_Empty,
        __Marshaller_wirehush_v1_ExitReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::WireHush.Protocol.WirehushReflection.Descriptor.Services[0]; }
    }

    /// <summary>Client for Manager</summary>
    public partial class ManagerClient : grpc::ClientBase<ManagerClient>
    {
      /// <summary>Creates a new client for Manager</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public ManagerClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Manager that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public ManagerClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected ManagerClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected ManagerClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::WireHush.Protocol.HandshakeReply Handshake(global::WireHush.Protocol.HandshakeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Handshake(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::WireHush.Protocol.HandshakeReply Handshake(global::WireHush.Protocol.HandshakeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Handshake, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::WireHush.Protocol.HandshakeReply> HandshakeAsync(global::WireHush.Protocol.HandshakeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return HandshakeAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::WireHush.Protocol.HandshakeReply> HandshakeAsync(global::WireHush.Protocol.HandshakeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Handshake, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::WireHush.Protocol.SnapshotReply Snapshot(global::WireHush.Protocol.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Snapshot(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::WireHush.Protocol.SnapshotReply Snapshot(global::WireHush.Protocol.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Snapshot, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::WireHush.Protocol.SnapshotReply> SnapshotAsync(global::WireHush.Protocol.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SnapshotAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::WireHush.Protocol.SnapshotReply> SnapshotAsync(global::WireHush.Protocol.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Snapshot, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::WireHush.Protocol.ConfigurationReply ReadConfiguration(global::WireHush.Protocol.TunnelRef request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ReadConfiguration(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::WireHush.Protocol.ConfigurationReply ReadConfiguration(global::WireHush.Protocol.TunnelRef request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ReadConfiguration, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::WireHush.Protocol.ConfigurationReply> ReadConfigurationAsync(global::WireHush.Protocol.TunnelRef request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ReadConfigurationAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::WireHush.Protocol.ConfigurationReply> ReadConfigurationAsync(global::WireHush.Protocol.TunnelRef request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ReadConfiguration, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::WireHush.Protocol.TunnelSnapshot CreateTunnel(global::WireHush.Protocol.CreateTunnelRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateTunnel(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::WireHush.Protocol.TunnelSnapshot CreateTunnel(global::WireHush.Protocol.CreateTunnelRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateTunnel, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::WireHush.Protocol.TunnelSnapshot> CreateTunnelAsync(global::WireHush.Protocol.CreateTunnelRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateTunnelAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::WireHush.Protocol.TunnelSnapshot> CreateTunnelAsync(global::WireHush.Protocol.CreateTunnelRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateTunnel, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::WireHush.Protocol.Empty UpdateTunnel(global::WireHush.Protocol.UpdateTunnelRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateTunnel(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::WireHush.Protocol.Empty UpdateTunnel(global::WireHush.Protocol.UpdateTunnelRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UpdateTunnel, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::WireHush.Protocol.Empty> UpdateTunnelAsync(global::WireHush.Protocol.UpdateTunnelRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateTunnelAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::WireHush.Protocol.Empty> UpdateTunnelAsync(global::WireHush.Protocol.UpdateTunnelRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UpdateTunnel, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::WireHush.Protocol.Empty DeleteTunnel(global::WireHush.Protocol.TunnelRef request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteTunnel(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::WireHush.Protocol.Empty DeleteTunnel(global::WireHush.Protocol.TunnelRef request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeleteTunnel, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::WireHush.Protocol.Empty> DeleteTunnelAsync(global::WireHush.Protocol.TunnelRef request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteTunnelAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::WireHush.Protocol.Empty> DeleteTunnelAsync(global::WireHush.Protocol.TunnelRef request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeleteTunnel, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::WireHush.Protocol.Empty StartTunnel(global::WireHush.Protocol.TunnelRef request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return StartTunnel(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::WireHush.Protocol.Empty StartTunnel(global::WireHush.Protocol.TunnelRef request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_StartTunnel, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::WireHush.Protocol.Empty> StartTunnelAsync(global::WireHush.Protocol.TunnelRef request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return StartTunnelAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::WireHush.Protocol.Empty> StartTunnelAsync(global::WireHush.Protocol.TunnelRef request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_StartTunnel, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::WireHush.Protocol.Empty StopTunnel(global::WireHush.Protocol.TunnelRef request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return StopTunnel(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::WireHush.Protocol.Empty StopTunnel(global::WireHush.Protocol.TunnelRef request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_StopTunnel, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::WireHush.Protocol.Empty> StopTunnelAsync(global::WireHush.Protocol.TunnelRef request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return StopTunnelAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::WireHush.Protocol.Empty> StopTunnelAsync(global::WireHush.Protocol.TunnelRef request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_StopTunnel, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::WireHush.Protocol.BootstrapSettings ReadBootstrap(global::WireHush.Protocol.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ReadBootstrap(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::WireHush.Protocol.BootstrapSettings ReadBootstrap(global::WireHush.Protocol.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ReadBootstrap, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::WireHush.Protocol.BootstrapSettings> ReadBootstrapAsync(global::WireHush.Protocol.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ReadBootstrapAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::WireHush.Protocol.BootstrapSettings> ReadBootstrapAsync(global::WireHush.Protocol.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ReadBootstrap, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::WireHush.Protocol.Empty SaveBootstrap(global::WireHush.Protocol.BootstrapSettings request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SaveBootstrap(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::WireHush.Protocol.Empty SaveBootstrap(global::WireHush.Protocol.BootstrapSettings request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SaveBootstrap, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::WireHush.Protocol.Empty> SaveBootstrapAsync(global::WireHush.Protocol.BootstrapSettings request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SaveBootstrapAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::WireHush.Protocol.Empty> SaveBootstrapAsync(global::WireHush.Protocol.BootstrapSettings request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SaveBootstrap, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::WireHush.Protocol.SnapshotReply> Subscribe(global::WireHush.Protocol.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Subscribe(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::WireHush.Protocol.SnapshotReply> Subscribe(global::WireHush.Protocol.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_Subscribe, null, options, request);
      }
      /// <summary>
      /// Stops only this caller's authorized active tunnel when safe; other sessions
      /// and other-user tunnels prevent whole-manager shutdown, never authorize it.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::WireHush.Protocol.ExitReply ExitSession(global::WireHush.Protocol.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ExitSession(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Stops only this caller's authorized active tunnel when safe; other sessions
      /// and other-user tunnels prevent whole-manager shutdown, never authorize it.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::WireHush.Protocol.ExitReply ExitSession(global::WireHush.Protocol.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ExitSession, null, options, request);
      }
      /// <summary>
      /// Stops only this caller's authorized active tunnel when safe; other sessions
      /// and other-user tunnels prevent whole-manager shutdown, never authorize it.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::WireHush.Protocol.ExitReply> ExitSessionAsync(global::WireHush.Protocol.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ExitSessionAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Stops only this caller's authorized active tunnel when safe; other sessions
      /// and other-user tunnels prevent whole-manager shutdown, never authorize it.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::WireHush.Protocol.ExitReply> ExitSessionAsync(global::WireHush.Protocol.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ExitSession, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override ManagerClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ManagerClient(configuration);
      }
    }

  }
}
#endregion
